package com.wardrobapp.presentation

import java.io.File
import javax.xml.parsers.DocumentBuilderFactory
import kotlin.test.Test
import kotlin.test.assertEquals
import kotlin.test.assertTrue

/**
 * The launcher icon is complete.
 *
 * Here, in a module that builds without the Android SDK, for the same reason
 * [StringResourceParityTest] is: `:app` cannot be compiled on a machine with no
 * SDK, so a test that reads its resources is the only check available before CI.
 *
 * What it is guarding against is the quiet kind of wrong. A missing density does
 * not fail a build -- Android scales the nearest one it can find -- so the first
 * sign is a blurry icon on somebody's phone. A raster the wrong size for the
 * folder it is in is worse, because it looks deliberate. And the adaptive icon is
 * three references to files that have to exist, none of which the manifest
 * checks.
 *
 * The rasters are generated by `scripts/generate-launcher-icons.py`; this is what
 * says the generator was run after the drawing changed.
 */
class LauncherIconTest {

    /** What Android expects at each density, in pixels. */
    private val densities = mapOf(
        "mipmap-mdpi" to 48,
        "mipmap-hdpi" to 72,
        "mipmap-xhdpi" to 96,
        "mipmap-xxhdpi" to 144,
        "mipmap-xxxhdpi" to 192,
    )

    private val names = listOf("ic_launcher.png", "ic_launcher_round.png")

    @Test
    fun `every density has both icons, at the size that density means`() {
        val failures = mutableListOf<String>()

        for ((folder, expected) in densities) {
            for (name in names) {
                val file = File(File(resourceDirectory(), folder), name)
                if (!file.isFile) {
                    failures += "$folder/$name is missing"
                    continue
                }

                val size = pngSize(file)
                if (size == null) {
                    failures += "$folder/$name is not a PNG"
                } else if (size.first != expected || size.second != expected) {
                    failures += "$folder/$name is ${size.first}x${size.second}, expected " +
                        "${expected}x$expected"
                }
            }
        }

        assertTrue(
            failures.isEmpty(),
            "run scripts/generate-launcher-icons.py:\n  " + failures.joinToString("\n  "),
        )
    }

    @Test
    fun `the adaptive icon names three layers that exist`() {
        for (name in listOf("ic_launcher.xml", "ic_launcher_round.xml")) {
            val file = File(File(resourceDirectory(), "mipmap-anydpi-v26"), name)
            assertTrue(file.isFile, "$name is missing, so Android 8 and up fall back to the raster")

            val document = DocumentBuilderFactory.newInstance()
                .also { it.isNamespaceAware = false }
                .newDocumentBuilder()
                .parse(file)

            // Every layer, including monochrome: without it, a phone with themed
            // icons turned on shows this app as a grey blob while every other icon
            // is tinted.
            for (layer in listOf("background", "foreground", "monochrome")) {
                val elements = document.getElementsByTagName(layer)
                assertEquals(1, elements.length, "$name has no <$layer>")

                val reference = (elements.item(0) as org.w3c.dom.Element)
                    .getAttribute("android:drawable")
                assertTrue(reference.isNotEmpty(), "$name's <$layer> names no drawable")
                assertTrue(
                    referencedResourceExists(reference),
                    "$name's <$layer> points at $reference, which does not exist",
                )
            }
        }
    }

    @Test
    fun `the icon background is the app's own colour`() {
        // Not a style point: it is also the launch background, and the two being
        // one value is what stops the splash flashing a different colour than the
        // icon it is drawn from. `#E6F4FE` here would mean the Expo template's
        // default had crept back in.
        val file = File(File(resourceDirectory(), "values"), "ic_launcher_background.xml")
        assertTrue(file.isFile, "no ic_launcher_background.xml")

        val colours = DocumentBuilderFactory.newInstance()
            .also { it.isNamespaceAware = false }
            .newDocumentBuilder()
            .parse(file)
            .getElementsByTagName("color")

        val named = (0 until colours.length)
            .map { colours.item(it) as org.w3c.dom.Element }
            .associate { it.getAttribute("name") to it.textContent.trim() }

        assertEquals("#6C63FF", named["ic_launcher_background"], "not the app's primary colour")
    }

    /**
     * Whether `@drawable/x` or `@color/x` names something that is there.
     *
     * Only the two kinds the adaptive icon uses. A vector may live in `drawable/`
     * as XML; a colour is a name inside a values file, so that is looked up by
     * name rather than by filename.
     */
    private fun referencedResourceExists(reference: String): Boolean {
        val (kind, name) = reference.removePrefix("@").split('/', limit = 2)
            .let { if (it.size == 2) it[0] to it[1] else return false }

        return when (kind) {
            "drawable" -> File(File(resourceDirectory(), "drawable"), "$name.xml").isFile ||
                File(File(resourceDirectory(), "drawable"), "$name.png").isFile
            "color" -> File(resourceDirectory(), "values")
                .listFiles()
                ?.any { it.extension == "xml" && it.readText().contains("name=\"$name\"") } == true
            else -> false
        }
    }

    /** The IHDR width and height of a PNG, or null if it is not one. */
    private fun pngSize(file: File): Pair<Int, Int>? {
        val header = file.inputStream().use { it.readNBytes(24) }
        if (header.size < 24) return null

        val signature = byteArrayOf(0x89.toByte(), 'P'.code.toByte(), 'N'.code.toByte(), 'G'.code.toByte())
        if (!header.copyOfRange(0, 4).contentEquals(signature)) return null

        // IHDR is required to be the first chunk, so the dimensions are at a fixed
        // offset: 8 signature + 4 length + 4 type.
        fun intAt(offset: Int): Int = (0..3).fold(0) { value, byte ->
            (value shl 8) or (header[offset + byte].toInt() and 0xff)
        }

        return intAt(16) to intAt(20)
    }

    private fun resourceDirectory(): File {
        val path = System.getProperty("appResDir")
            ?: error("appResDir was not set; see presentation/build.gradle.kts")
        return File(path)
    }
}
