package com.wardrobapp.presentation

import java.io.File
import javax.xml.parsers.DocumentBuilderFactory
import kotlin.math.hypot
import kotlin.test.Test
import kotlin.test.assertEquals
import kotlin.test.assertTrue

/**
 * The launcher icon is complete.
 *
 * Here, in a module that builds without the Android SDK, for the same reason
 * [StringResourceParityTest] is: `:app` cannot be compiled on a machine with no
 * SDK, so a test that reads its resources is the only check available before CI.
 *
 * What it is guarding against is the quiet kind of wrong. A missing density does
 * not fail a build -- Android scales the nearest one it can find -- so the first
 * sign is a blurry icon on somebody's phone. A raster the wrong size for the
 * folder it is in is worse, because it looks deliberate. And the adaptive icon is
 * three references to files that have to exist, none of which the manifest
 * checks.
 *
 * The drawing itself is checked for the two ways it can be quietly wrong as well:
 * artwork that a round mask would clip, and a themed layer that has drifted from
 * the foreground it is a copy of. Both of those look fine in the file and wrong on
 * a phone, and only on some phones.
 *
 * The rasters are generated by `scripts/generate-launcher-icons.py`, which reads
 * the same vector; this is what says the generator was run after the drawing
 * changed.
 */
class LauncherIconTest {

    /** What Android expects at each density, in pixels. */
    private val densities = mapOf(
        "mipmap-mdpi" to 48,
        "mipmap-hdpi" to 72,
        "mipmap-xhdpi" to 96,
        "mipmap-xxhdpi" to 144,
        "mipmap-xxxhdpi" to 192,
    )

    private val names = listOf("ic_launcher.png", "ic_launcher_round.png")

    @Test
    fun `every density has both icons, at the size that density means`() {
        val failures = mutableListOf<String>()

        for ((folder, expected) in densities) {
            for (name in names) {
                val file = File(File(resourceDirectory(), folder), name)
                if (!file.isFile) {
                    failures += "$folder/$name is missing"
                    continue
                }

                val size = pngSize(file)
                if (size == null) {
                    failures += "$folder/$name is not a PNG"
                } else if (size.first != expected || size.second != expected) {
                    failures += "$folder/$name is ${size.first}x${size.second}, expected " +
                        "${expected}x$expected"
                }
            }
        }

        assertTrue(
            failures.isEmpty(),
            "run scripts/generate-launcher-icons.py:\n  " + failures.joinToString("\n  "),
        )
    }

    @Test
    fun `the adaptive icon names three layers that exist`() {
        for (name in listOf("ic_launcher.xml", "ic_launcher_round.xml")) {
            val file = File(File(resourceDirectory(), "mipmap-anydpi-v26"), name)
            assertTrue(file.isFile, "$name is missing, so Android 8 and up fall back to the raster")

            val document = DocumentBuilderFactory.newInstance()
                .also { it.isNamespaceAware = false }
                .newDocumentBuilder()
                .parse(file)

            // Every layer, including monochrome: without it, a phone with themed
            // icons turned on shows this app as a grey blob while every other icon
            // is tinted.
            for (layer in listOf("background", "foreground", "monochrome")) {
                val elements = document.getElementsByTagName(layer)
                assertEquals(1, elements.length, "$name has no <$layer>")

                val reference = (elements.item(0) as org.w3c.dom.Element)
                    .getAttribute("android:drawable")
                assertTrue(reference.isNotEmpty(), "$name's <$layer> names no drawable")
                assertTrue(
                    referencedResourceExists(reference),
                    "$name's <$layer> points at $reference, which does not exist",
                )
            }
        }
    }

    @Test
    fun `the icon background is the cream the logo is printed on`() {
        // Not a style point. The mark is a taupe thread drawn for a cream ground,
        // and on anything else it is a different logo: `#6C63FF` here would be the
        // violet that belonged to the t-shirt this replaced, and `#E6F4FE` would
        // mean the Expo template's default had crept back in.
        val file = File(File(resourceDirectory(), "values"), "ic_launcher_background.xml")
        assertTrue(file.isFile, "no ic_launcher_background.xml")

        assertEquals(
            "#F3EDE3",
            colours(file)["ic_launcher_background"],
            "not the colour the monogram was drawn for",
        )
    }

    @Test
    fun `the splash follows the theme and the icon does not`() {
        // These two were one value once, which was right while the icon was white
        // on violet: the splash could be the icon's own background and neither
        // could flash a colour the other did not have.
        //
        // A cream icon breaks that. Cream is the correct window on a light phone
        // and is the white flash on a dark one, so the splash needs a night
        // variant -- and the icon must not have one, because a launcher icon that
        // changes colour with the system theme is two icons. Hence two colours,
        // equal in values/ and different in values-night/, which is exactly the
        // arrangement somebody tidying up would collapse back into one.
        val day = File(File(resourceDirectory(), "values"), "splash_background.xml")
        val night = File(File(resourceDirectory(), "values-night"), "splash_background.xml")
        assertTrue(day.isFile, "no values/splash_background.xml")
        assertTrue(night.isFile, "no values-night/splash_background.xml, so a dark phone flashes cream")

        val icon = colours(File(File(resourceDirectory(), "values"), "ic_launcher_background.xml"))
        assertEquals(
            icon["ic_launcher_background"],
            colours(day)["splash_background"],
            "the light splash is not the icon's background, so the two show a seam",
        )
        assertTrue(
            colours(night)["splash_background"] != colours(day)["splash_background"],
            "the night splash is the light one, which is the flash it exists to prevent",
        )
        assertTrue(
            !File(resourceDirectory(), "values-night").resolve("ic_launcher_background.xml").isFile,
            "the icon's background has a night variant, so the app has two launcher icons",
        )
    }

    @Test
    fun `the monogram stays inside the circle a launcher may mask it to`() {
        // The 108x108 canvas promises very little. Launchers mask it to a shape of
        // their own -- circle, squircle, teardrop -- and each of those sits inside
        // a circle of radius 36 about the centre, so that circle is the real
        // boundary rather than the 72x72 square usually quoted. The needle's point
        // is the part that would go first, and a clipped point reads as a mistake
        // rather than as a mask.
        //
        // Control points, not the curve: a cubic never leaves the convex hull of
        // its own control points, so a hull inside the circle puts the curve inside
        // it too. That is stricter than necessary -- a control point may sit well
        // outside the line it bends -- which for a safe zone is the direction to be
        // wrong in, and it is what lets this check be a regex rather than a
        // rasterizer.
        for ((data, stroke) in paths(foreground())) {
            for ((x, y) in coordinates(data)) {
                // Half the stroke, because a path is a centre line and the ink
                // reaches that far either side of it.
                val reach = hypot(x - 54.0, y - 54.0) + stroke / 2
                assertTrue(
                    reach <= MASK_RADIUS,
                    "a control point at ($x, $y) reaches ${"%.1f".format(reach)} from the " +
                        "centre, past the $MASK_RADIUS a round mask leaves",
                )
            }
        }
    }

    @Test
    fun `the themed layer is the same drawing as the foreground`() {
        // Two files holding one drawing, because the system tints this one and so
        // its ink has to be black rather than the taupe next door -- which leaves
        // the copy that goes stale in silence. Nothing in the manifest or the build
        // compares them; a phone with themed icons turned on is otherwise the first
        // thing to notice.
        val monochrome = File(File(resourceDirectory(), "drawable"), "ic_launcher_monochrome.xml")
        assertTrue(monochrome.isFile, "no ic_launcher_monochrome.xml")

        assertEquals(
            paths(foreground()),
            paths(monochrome),
            "the monochrome layer has drifted from the foreground; copy the paths across",
        )
    }

    /** The radius every mask shape fits inside, on the 108-unit canvas. */
    private val MASK_RADIUS = 36.0

    private fun foreground() = File(File(resourceDirectory(), "drawable"), "ic_launcher_foreground.xml")

    /** Each `<path>` in a vector drawable as its data and its stroke width. */
    private fun paths(file: File): List<Pair<String, Double>> {
        val elements = parse(file).getElementsByTagName("path")
        return (0 until elements.length)
            .map { elements.item(it) as org.w3c.dom.Element }
            .map { it.getAttribute("android:pathData") to
                (it.getAttribute("android:strokeWidth").toDoubleOrNull() ?: 0.0) }
    }

    /**
     * The coordinate pairs in a `pathData` string.
     *
     * Every command this drawing uses -- `M`, `L`, `C`, `Z` -- takes whole
     * coordinate pairs and nothing else, so the numbers can be read in twos
     * without parsing the commands around them. An arc or a `H` would break that
     * assumption, and would have to be handled here if one ever appeared.
     */
    private fun coordinates(data: String): List<Pair<Double, Double>> {
        val numbers = Regex("-?\\d+(\\.\\d+)?").findAll(data).map { it.value.toDouble() }.toList()
        assertEquals(0, numbers.size % 2, "a pathData with an odd number of numbers in it")
        return numbers.chunked(2).map { it[0] to it[1] }
    }

    private fun colours(file: File): Map<String, String> {
        val elements = parse(file).getElementsByTagName("color")
        return (0 until elements.length)
            .map { elements.item(it) as org.w3c.dom.Element }
            .associate { it.getAttribute("name") to it.textContent.trim() }
    }

    private fun parse(file: File) = DocumentBuilderFactory.newInstance()
        .also { it.isNamespaceAware = false }
        .newDocumentBuilder()
        .parse(file)

    /**
     * Whether `@drawable/x` or `@color/x` names something that is there.
     *
     * Only the two kinds the adaptive icon uses. A vector may live in `drawable/`
     * as XML; a colour is a name inside a values file, so that is looked up by
     * name rather than by filename.
     */
    private fun referencedResourceExists(reference: String): Boolean {
        val (kind, name) = reference.removePrefix("@").split('/', limit = 2)
            .let { if (it.size == 2) it[0] to it[1] else return false }

        return when (kind) {
            "drawable" -> File(File(resourceDirectory(), "drawable"), "$name.xml").isFile ||
                File(File(resourceDirectory(), "drawable"), "$name.png").isFile
            "color" -> File(resourceDirectory(), "values")
                .listFiles()
                ?.any { it.extension == "xml" && it.readText().contains("name=\"$name\"") } == true
            else -> false
        }
    }

    /** The IHDR width and height of a PNG, or null if it is not one. */
    private fun pngSize(file: File): Pair<Int, Int>? {
        val header = file.inputStream().use { it.readNBytes(24) }
        if (header.size < 24) return null

        val signature = byteArrayOf(0x89.toByte(), 'P'.code.toByte(), 'N'.code.toByte(), 'G'.code.toByte())
        if (!header.copyOfRange(0, 4).contentEquals(signature)) return null

        // IHDR is required to be the first chunk, so the dimensions are at a fixed
        // offset: 8 signature + 4 length + 4 type.
        fun intAt(offset: Int): Int = (0..3).fold(0) { value, byte ->
            (value shl 8) or (header[offset + byte].toInt() and 0xff)
        }

        return intAt(16) to intAt(20)
    }

    private fun resourceDirectory(): File {
        val path = System.getProperty("appResDir")
            ?: error("appResDir was not set; see presentation/build.gradle.kts")
        return File(path)
    }
}
