export const CATEGORIES = {
  tops: {
    label: 'Tops',
    subcategories: ['T-Shirt', 'Blouse', 'Shirt', 'Tank Top', 'Sweater', 'Hoodie', 'Crop Top', 'Polo'],
    icon: 'shirt',
  },
  bottoms: {
    label: 'Bottoms',
    subcategories: ['Jeans', 'Pants', 'Shorts', 'Skirt', 'Leggings', 'Sweatpants', 'Chinos'],
    icon: 'pricetag',
  },
  dresses: {
    label: 'Dresses',
    subcategories: ['Mini', 'Midi', 'Maxi', 'Cocktail', 'Sundress', 'Jumpsuit', 'Romper'],
    icon: 'body',
  },
  midlayer: {
    label: 'Mid-Layer',
    subcategories: ['Blazer', 'Vest', 'Poncho', 'Cape'],
    icon: 'albums',
  },
  outerwear: {
    label: 'Outerwear',
    subcategories: ['Jacket', 'Coat', 'Cardigan', 'Windbreaker', 'Parka'],
    icon: 'cloudy',
  },
  shoes: {
    label: 'Shoes',
    subcategories: ['Sneakers', 'Boots', 'Sandals', 'Heels', 'Flats', 'Loafers', 'Athletic'],
    icon: 'footsteps',
  },
  accessories: {
    label: 'Accessories',
    subcategories: ['Hat', 'Scarf', 'Belt', 'Bag', 'Jewelry', 'Watch', 'Sunglasses', 'Tie'],
    icon: 'diamond',
  },
  activewear: {
    label: 'Activewear',
    subcategories: ['Sports Bra', 'Workout Top', 'Workout Shorts', 'Yoga Pants', 'Track Suit'],
    icon: 'fitness',
  },
  underwear: {
    label: 'Underwear',
    subcategories: ['Bra', 'Briefs', 'Boxers', 'Bodysuit', 'Shapewear', 'Socks', 'Tights', 'Thermal'],
    icon: 'layers',
  },
  loungewear: {
    label: 'Loungewear/Pajamas',
    subcategories: ['Pajama Set', 'Pajama Top', 'Pajama Bottoms', 'Nightgown', 'Robe', 'Lounge Set'],
    icon: 'moon',
  },
} as const;

export const COMMON_TAGS = [
  'Short Sleeve', 'Long Sleeve', 'Sleeveless',
  'Business', 'Sporty',
  'Cotton', 'Polyester', 'Linen', 'Silk', 'Wool', 'Denim', 'Leather',
  'Slim Fit', 'Regular Fit', 'Oversized', 'Fitted',
  'Patterned', 'Striped', 'Solid', 'Floral', 'Plaid',
  'High-Waist', 'Low-Waist', 'Mid-Rise',
  'Mini', 'Midi', 'Maxi',
  'Vintage', 'Trendy', 'Classic', 'Statement',
  'Waterproof', 'Lightweight', 'Heavy',
];

export const COMMON_TAGS_ES = [
  'Manga Corta', 'Manga Larga', 'Sin Mangas',
  'Formal', 'Deportivo',
  'Algodón', 'Poliéster', 'Lino', 'Seda', 'Lana', 'Mezclilla', 'Cuero',
  'Ajustado', 'Corte Regular', 'Holgado', 'Entallado',
  'Estampado', 'A Rayas', 'Liso', 'Floral', 'Cuadros',
  'Cintura Alta', 'Cintura Baja', 'Tiro Medio',
  'Mini', 'Midi', 'Maxi',
  'Vintage', 'De Tendencia', 'Clásico', 'Llamativo',
  'Impermeable', 'Ligero', 'Grueso',
];

export const COMMON_SIZES = [
  'XXS', 'XS', 'S', 'M', 'L', 'XL', 'XXL', 'XXXL',
  '0', '2', '4', '6', '8', '10', '12', '14', '16',
  '28', '29', '30', '31', '32', '33', '34', '36', '38', '40',
  '5', '5.5', '6', '6.5', '7', '7.5', '8', '8.5', '9', '9.5', '10', '10.5', '11', '12', '13',
  'One Size',
];

export const SUBCATEGORY_KEY_MAP: Record<string, string> = {
  'T-Shirt': 'tshirt',
  'Blouse': 'blouse',
  'Shirt': 'shirt',
  'Tank Top': 'tank_top',
  'Sweater': 'sweater',
  'Hoodie': 'hoodie',
  'Crop Top': 'crop_top',
  'Polo': 'polo',
  'Jeans': 'jeans',
  'Pants': 'pants',
  'Shorts': 'shorts',
  'Skirt': 'skirt',
  'Leggings': 'leggings',
  'Sweatpants': 'sweatpants',
  'Chinos': 'chinos',
  'Mini': 'mini',
  'Midi': 'midi',
  'Maxi': 'maxi',
  'Cocktail': 'cocktail',
  'Sundress': 'sundress',
  'Jumpsuit': 'jumpsuit',
  'Romper': 'romper',
  'Jacket': 'jacket',
  'Coat': 'coat',
  'Blazer': 'blazer',
  'Cardigan': 'cardigan',
  'Vest': 'vest',
  'Poncho': 'poncho',
  'Cape': 'cape',
  'Windbreaker': 'windbreaker',
  'Parka': 'parka',
  'Sneakers': 'sneakers',
  'Boots': 'boots',
  'Sandals': 'sandals',
  'Heels': 'heels',
  'Flats': 'flats',
  'Loafers': 'loafers',
  'Athletic': 'athletic',
  'Hat': 'hat',
  'Scarf': 'scarf',
  'Belt': 'belt',
  'Bag': 'bag',
  'Jewelry': 'jewelry',
  'Watch': 'watch',
  'Sunglasses': 'sunglasses',
  'Tie': 'tie',
  'Sports Bra': 'sports_bra',
  'Workout Top': 'workout_top',
  'Workout Shorts': 'workout_shorts',
  'Yoga Pants': 'yoga_pants',
  'Track Suit': 'track_suit',
  'Bra': 'bra',
  'Briefs': 'briefs',
  'Boxers': 'boxers',
  'Bodysuit': 'bodysuit',
  'Shapewear': 'shapewear',
  'Socks': 'socks',
  'Tights': 'tights',
  'Thermal': 'thermal',
  'Pajama Set': 'pajama_set',
  'Pajama Top': 'pajama_top',
  'Pajama Bottoms': 'pajama_bottoms',
  'Nightgown': 'nightgown',
  'Robe': 'robe',
  'Lounge Set': 'lounge_set',
};
