export const GARMENT_COLORS = [
  { key: 'black', hex: '#000000' },
  { key: 'white', hex: '#FFFFFF' },
  { key: 'gray', hex: '#808080' },
  { key: 'navy', hex: '#000080' },
  { key: 'blue', hex: '#0066CC' },
  { key: 'lightBlue', hex: '#87CEEB' },
  { key: 'red', hex: '#CC0000' },
  { key: 'burgundy', hex: '#800020' },
  { key: 'pink', hex: '#FF69B4' },
  { key: 'green', hex: '#228B22' },
  { key: 'olive', hex: '#808000' },
  { key: 'khaki', hex: '#C3B091' },
  { key: 'brown', hex: '#8B4513' },
  { key: 'tan', hex: '#D2B48C' },
  { key: 'beige', hex: '#F5F5DC' },
  { key: 'cream', hex: '#FFFDD0' },
  { key: 'yellow', hex: '#FFD700' },
  { key: 'orange', hex: '#FF8C00' },
  { key: 'purple', hex: '#800080' },
  { key: 'lavender', hex: '#E6E6FA' },
  { key: 'coral', hex: '#FF7F50' },
  { key: 'teal', hex: '#008080' },
  { key: 'gold', hex: '#DAA520' },
  { key: 'silver', hex: '#C0C0C0' },
  { key: 'multi', hex: '#RAINBOW' },
] as const;

export type GarmentColorName = (typeof GARMENT_COLORS)[number]['key'];
