// Generated by scripts/generate-glyphs.py from art/glyphs/*.svg. Do not edit:
// change the SVG and run the script. GlyphSourcesTest fails until the two agree.

package com.wardrobapp.app

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.PathFillType
import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.PathNode
import androidx.compose.ui.graphics.vector.addPathNodes
import androidx.compose.ui.unit.dp

/**
 * The vendored glyphs, as vectors built in code.
 *
 * Reached through [Glyph] rather than directly, which is where the reasoning
 * lives. Each is built on first use and kept: twenty-three small vectors, most
 * of which a given session never draws.
 */
internal object GlyphVectors {

    val Apps: ImageVector by lazy {
        glyph(
            path("M4 8h4V4H4v4zm6 12h4v-4h-4v4zm-6 0h4v-4H4v4zm0-6h4v-4H4v4zm6 0h4v-4h-4v4zm6-10v4h4V4h-4zm-6 4h4V4h-4v4zm6 6h4v-4h-4v4zm0 6h4v-4h-4v4z"),
        )
    }

    val Archive: ImageVector by lazy {
        glyph(
            path("M20.54 5.23l-1.39-1.68C18.88 3.21 18.47 3 18 3H6c-.47 0-.88.21-1.16.55L3.46 5.23C3.17 5.57 3 6.02 3 6.5V19c0 1.1.9 2 2 2h14c1.1 0 2-.9 2-2V6.5c0-.48-.17-.93-.46-1.27zM12 17.5L6.5 12H10v-2h4v2h3.5L12 17.5zM5.12 5l.81-1h12l.94 1H5.12z"),
        )
    }

    val AutoAwesome: ImageVector by lazy {
        glyph(
            path("M19 9l1.25-2.75L23 5l-2.75-1.25L19 1l-1.25 2.75L15 5l2.75 1.25L19 9zm-7.5.5L9 4 6.5 9.5 1 12l5.5 2.5L9 20l2.5-5.5L17 12l-5.5-2.5zM19 15l-1.25 2.75L15 19l2.75 1.25L19 23l1.25-2.75L23 19l-2.75-1.25L19 15z"),
        )
    }

    val AutoFixHigh: ImageVector by lazy {
        glyph(
            path("M7.5 5.6L10 7 8.6 4.5 10 2 7.5 3.4 5 2l1.4 2.5L5 7zm12 9.8L17 14l1.4 2.5L17 19l2.5-1.4L22 19l-1.4-2.5L22 14zM22 2l-2.5 1.4L17 2l1.4 2.5L17 7l2.5-1.4L22 7l-1.4-2.5zm-7.63 5.29c-.39-.39-1.02-.39-1.41 0L1.29 18.96c-.39.39-.39 1.02 0 1.41l2.34 2.34c.39.39 1.02.39 1.41 0L16.7 11.05c.39-.39.39-1.02 0-1.41l-2.33-2.35zm-1.03 5.49l-2.12-2.12 2.44-2.44 2.12 2.12-2.44 2.44z"),
        )
    }

    val Bookmark: ImageVector by lazy {
        glyph(
            path("M17 3H7c-1.1 0-1.99.9-1.99 2L5 21l7-3 7 3V5c0-1.1-.9-2-2-2z"),
        )
    }

    val BookmarkBorder: ImageVector by lazy {
        glyph(
            path("M17 3H7c-1.1 0-1.99.9-1.99 2L5 21l7-3 7 3V5c0-1.1-.9-2-2-2zm0 15l-5-2.18L7 18V5h10v13z"),
        )
    }

    val ChevronRight: ImageVector by lazy {
        glyph(
            path("M10 6L8.59 7.41 13.17 12l-4.58 4.59L10 18l6-6z"),
        )
    }

    val Crop: ImageVector by lazy {
        glyph(
            path("M17 15h2V7c0-1.1-.9-2-2-2H9v2h8v8zM7 17V1H5v4H1v2h4v10c0 1.1.9 2 2 2h10v4h2v-4h4v-2H7z"),
        )
    }

    val DeleteOutline: ImageVector by lazy {
        glyph(
            path("M6 19c0 1.1.9 2 2 2h8c1.1 0 2-.9 2-2V7H6v12zM8 9h8v10H8V9zm7.5-5l-1-1h-5l-1 1H5v2h14V4z"),
        )
    }

    val Download: ImageVector by lazy {
        glyph(
            path("M5,20h14v-2H5V20z M19,9h-4V3H9v6H5l7,7L19,9z"),
        )
    }

    val ExpandMore: ImageVector by lazy {
        glyph(
            path("M16.59 8.59L12 13.17 7.41 8.59 6 10l6 6 6-6z"),
        )
    }

    val GridView: ImageVector by lazy {
        glyph(
            path("M3 3v8h8V3H3zm6 6H5V5h4v4zm-6 4v8h8v-8H3zm6 6H5v-4h4v4zm4-16v8h8V3h-8zm6 6h-4V5h4v4zm-6 4v8h8v-8h-8zm6 6h-4v-4h4v4z", evenOdd = true),
        )
    }

    val Insights: ImageVector by lazy {
        glyph(
            path("M21,8c-1.45,0-2.26,1.44-1.93,2.51l-3.55,3.56c-0.3-0.09-0.74-0.09-1.04,0l-2.55-2.55C12.27,10.45,11.46,9,10,9 c-1.45,0-2.27,1.44-1.93,2.52l-4.56,4.55C2.44,15.74,1,16.55,1,18c0,1.1,0.9,2,2,2c1.45,0,2.26-1.44,1.93-2.51l4.55-4.56 c0.3,0.09,0.74,0.09,1.04,0l2.55,2.55C12.73,16.55,13.54,18,15,18c1.45,0,2.27-1.44,1.93-2.52l3.56-3.55 C21.56,12.26,23,11.45,23,10C23,8.9,22.1,8,21,8z"),
            path("M15,9 L15.94,6.93 L18,6 L15.94,5.07 L15,3 L14.08,5.07 L12,6 L14.08,6.93z"),
            path("M3.5,11 L4,9 L6,8.5 L4,8 L3.5,6 L3,8 L1,8.5 L3,9z"),
        )
    }

    val Link: ImageVector by lazy {
        glyph(
            path("M3.9 12c0-1.71 1.39-3.1 3.1-3.1h4V7H7c-2.76 0-5 2.24-5 5s2.24 5 5 5h4v-1.9H7c-1.71 0-3.1-1.39-3.1-3.1zM8 13h8v-2H8v2zm9-6h-4v1.9h4c1.71 0 3.1 1.39 3.1 3.1s-1.39 3.1-3.1 3.1h-4V17h4c2.76 0 5-2.24 5-5s-2.24-5-5-5z"),
        )
    }

    val PhotoCamera: ImageVector by lazy {
        glyph(
            path("M8.8,12.0 a3.2,3.2 0 1,0 6.4,0 a3.2,3.2 0 1,0 -6.4,0z"),
            path("M9 2L7.17 4H4c-1.1 0-2 .9-2 2v12c0 1.1.9 2 2 2h16c1.1 0 2-.9 2-2V6c0-1.1-.9-2-2-2h-3.17L15 2H9zm3 15c-2.76 0-5-2.24-5-5s2.24-5 5-5 5 2.24 5 5-2.24 5-5 5z"),
        )
    }

    val PushPin: ImageVector by lazy {
        glyph(
            path("M16,9V4l1,0c0.55,0,1-0.45,1-1v0c0-0.55-0.45-1-1-1H7C6.45,2,6,2.45,6,3v0 c0,0.55,0.45,1,1,1l1,0v5c0,1.66-1.34,3-3,3h0v2h5.97v7l1,1l1-1v-7H19v-2h0C17.34,12,16,10.66,16,9z", evenOdd = true),
        )
    }

    val RadioButtonUnchecked: ImageVector by lazy {
        glyph(
            path("M12 2C6.48 2 2 6.48 2 12s4.48 10 10 10 10-4.48 10-10S17.52 2 12 2zm0 18c-4.42 0-8-3.58-8-8s3.58-8 8-8 8 3.58 8 8-3.58 8-8 8z"),
        )
    }

    val RestartAlt: ImageVector by lazy {
        glyph(
            path("M12,5V2L8,6l4,4V7c3.31,0,6,2.69,6,6c0,2.97-2.17,5.43-5,5.91v2.02c3.95-0.49,7-3.85,7-7.93C20,8.58,16.42,5,12,5z"),
            path("M6,13c0-1.65,0.67-3.15,1.76-4.24L6.34,7.34C4.9,8.79,4,10.79,4,13c0,4.08,3.05,7.44,7,7.93v-2.02 C8.17,18.43,6,15.97,6,13z"),
        )
    }

    val SkipNext: ImageVector by lazy {
        glyph(
            path("M6 18l8.5-6L6 6v12zM16 6v12h2V6h-2z"),
        )
    }

    val StarBorder: ImageVector by lazy {
        glyph(
            path("M22 9.24l-7.19-.62L12 2 9.19 8.63 2 9.24l5.46 4.73L5.82 21 12 17.27 18.18 21l-1.63-7.03L22 9.24zM12 15.4l-3.76 2.27 1-4.28-3.32-2.88 4.38-.38L12 6.1l1.71 4.04 4.38.38-3.32 2.88 1 4.28L12 15.4z"),
        )
    }

    val SwapVert: ImageVector by lazy {
        glyph(
            path("M16 17.01V10h-2v7.01h-3L15 21l4-3.99h-3zM9 3L5 6.99h3V14h2V6.99h3L9 3z"),
        )
    }

    val Tune: ImageVector by lazy {
        glyph(
            path("M3 17v2h6v-2H3zM3 5v2h10V5H3zm10 16v-2h8v-2h-8v-2h-2v6h2zM7 9v2H3v2h4v2h2V9H7zm14 4v-2H11v2h10zm-6-4h2V7h4V5h-4V3h-2v6z"),
        )
    }

    val ViewModule: ImageVector by lazy {
        glyph(
            path("M14.67,5v6.5H9.33V5H14.67z M15.67,11.5H21V5h-5.33V11.5z M14.67,19v-6.5H9.33V19H14.67z M15.67,12.5V19H21v-6.5H15.67z M8.33,12.5H3V19h5.33V12.5z M8.33,11.5V5H3v6.5H8.33z"),
        )
    }
}

/** One path of a glyph: its outline, and how overlapping parts of it fill. */
private class GlyphPath(val nodes: List<PathNode>, val fillType: PathFillType)

private fun path(data: String, evenOdd: Boolean = false) =
    GlyphPath(addPathNodes(data), if (evenOdd) PathFillType.EvenOdd else PathFillType.NonZero)

/**
 * A 24dp glyph from its paths.
 *
 * White, as the drawables were, because every use tints it: `Icon` draws with
 * the content colour, and the fill only has to be opaque for that to work.
 */
private fun glyph(vararg paths: GlyphPath): ImageVector =
    ImageVector.Builder(
        defaultWidth = 24.dp,
        defaultHeight = 24.dp,
        viewportWidth = 24f,
        viewportHeight = 24f,
    ).apply {
        for (path in paths) {
            addPath(pathData = path.nodes, pathFillType = path.fillType, fill = SolidColor(Color.White))
        }
    }.build()
