#!/usr/bin/env python3
"""
Turn the vendored glyphs into Compose vectors.

    python3 scripts/generate-glyphs.py

Reads every `art/glyphs/*.svg` and writes one Kotlin file of `ImageVector`s,
named after the files: `swap_vert.svg` becomes `GlyphVectors.SwapVert`.

Why the glyphs are code rather than drawables. They used to be vector drawables
under `res/drawable`, which is Android's resource system, and the screens are
moving to Compose Multiplatform, where common code has no `R.drawable` to load
them from. An `ImageVector` built in Kotlin draws the same on every platform,
needs no resource lookup, and a missing glyph is a compile error rather than a
crash in the middle of composing a screen. It is the approach
TimoPtr/mdi-icons takes for the whole Material Design Icons catalogue; this is
the same idea for the twenty-three this app uses.

Why not that library, or material-icons-extended. The library is the
Pictogrammers set, whose drawings are not Google's Material glyphs the app is
designed with -- `swap-vertical` is not `swap_vert`. And material-icons-extended
carries every glyph Google has drawn in order to hand this app twenty-three,
which is the trade `Glyphs.kt` already explains refusing.

Why SVG as the source. It is what Google publishes the glyphs as, so a new one
is a file copied from upstream rather than a conversion, and each file says in
a comment which upstream file it came from and under what licence.

What it accepts is deliberately narrow: a 24 by 24 viewBox and filled paths,
optionally even-odd. That is everything the glyphs are, and anything else -- a
stroke, a group, a transform -- would be drawn wrong by a generator that ignored
it, so it is refused with the file named instead.

The output's path data is checked against these files by `GlyphSourcesTest` in
:presentation, so an SVG changed without running this fails the build, and
`GlyphVectorsTest` in :ui builds every one, so path data the generator let
through but Compose cannot parse fails there rather than on a screen.

No dependencies, like the launcher icon script beside it.
"""

from __future__ import annotations

import re
import sys
import xml.etree.ElementTree as ET
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SOURCES = ROOT / 'art' / 'glyphs'
OUTPUT = ROOT / 'ui' / 'src' / 'commonMain' / 'kotlin' / 'com' / 'wardrobapp' / 'ui' / 'GlyphVectors.kt'

SVG = '{http://www.w3.org/2000/svg}'

# Path data is written into a Kotlin string literal, so it may only hold what
# path data holds. A `$` or a quote would be Kotlin syntax rather than geometry.
PATH_DATA = re.compile(r'^[MmLlHhVvCcSsQqTtAaZz0-9eE.,\- \n]+$')


class GlyphError(Exception):
    pass


def kotlin_name(stem: str) -> str:
    """`radio_button_unchecked` -> `RadioButtonUnchecked`."""
    if not re.fullmatch(r'[a-z][a-z0-9]*(_[a-z0-9]+)*', stem):
        raise GlyphError(f'{stem}.svg: name it in snake_case, the way Material names glyphs')
    return ''.join(part.capitalize() for part in stem.split('_'))


def read_glyph(path: Path) -> list[tuple[str, bool]]:
    """Each path's data and whether it fills even-odd, in drawing order."""
    try:
        root = ET.parse(path).getroot()
    except ET.ParseError as error:
        # Usually a `--` inside a comment, which XML forbids.
        raise GlyphError(f'{path.name}: not well-formed XML ({error})') from None

    if root.tag != f'{SVG}svg':
        raise GlyphError(f'{path.name}: the root element is not <svg>')
    if root.get('viewBox') != '0 0 24 24':
        raise GlyphError(f'{path.name}: viewBox must be "0 0 24 24", not {root.get("viewBox")!r}')

    paths = []
    for element in root:
        if element.tag != f'{SVG}path':
            raise GlyphError(f'{path.name}: only <path> elements are drawn, found <{element.tag.replace(SVG, "")}>')
        unexpected = set(element.attrib) - {'d', 'fill-rule'}
        if unexpected:
            raise GlyphError(f'{path.name}: path attributes this cannot draw: {sorted(unexpected)}')

        rule = element.get('fill-rule', 'nonzero')
        if rule not in ('nonzero', 'evenodd'):
            raise GlyphError(f'{path.name}: fill-rule {rule!r} is not nonzero or evenodd')

        data = ' '.join(element.get('d', '').split())
        if not data or not PATH_DATA.match(data):
            raise GlyphError(f'{path.name}: path data is empty or holds something that is not path data')
        paths.append((data, rule == 'evenodd'))

    if not paths:
        raise GlyphError(f'{path.name}: no paths')
    return paths


def render(glyphs: dict[str, list[tuple[str, bool]]]) -> str:
    entries = []
    for name, paths in glyphs.items():
        calls = ',\n'.join(
            f'            path("{data}"' + (', evenOdd = true' if even_odd else '') + ')'
            for data, even_odd in paths
        )
        entries.append(f'    val {name}: ImageVector by lazy {{\n        glyph(\n{calls},\n        )\n    }}')

    return '''// Generated by scripts/generate-glyphs.py from art/glyphs/*.svg. Do not edit:
// change the SVG and run the script. GlyphSourcesTest fails until the two agree.

package com.wardrobapp.ui

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.PathFillType
import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.PathNode
import androidx.compose.ui.graphics.vector.addPathNodes
import androidx.compose.ui.unit.dp

/**
 * The vendored glyphs, as vectors built in code.
 *
 * Reached through [Glyph] rather than directly, which is where the reasoning
 * lives. Each is built on first use and kept: twenty-three small vectors, most
 * of which a given session never draws.
 */
internal object GlyphVectors {

''' + '\n\n'.join(entries) + '''
}

/** One path of a glyph: its outline, and how overlapping parts of it fill. */
private class GlyphPath(val nodes: List<PathNode>, val fillType: PathFillType)

private fun path(data: String, evenOdd: Boolean = false) =
    GlyphPath(addPathNodes(data), if (evenOdd) PathFillType.EvenOdd else PathFillType.NonZero)

/**
 * A 24dp glyph from its paths.
 *
 * White, as the drawables were, because every use tints it: `Icon` draws with
 * the content colour, and the fill only has to be opaque for that to work.
 */
private fun glyph(vararg paths: GlyphPath): ImageVector =
    ImageVector.Builder(
        defaultWidth = 24.dp,
        defaultHeight = 24.dp,
        viewportWidth = 24f,
        viewportHeight = 24f,
    ).apply {
        for (path in paths) {
            addPath(pathData = path.nodes, pathFillType = path.fillType, fill = SolidColor(Color.White))
        }
    }.build()
'''


def main() -> int:
    sources = sorted(SOURCES.glob('*.svg'))
    if not sources:
        print(f'no glyphs in {SOURCES}', file=sys.stderr)
        return 1

    try:
        glyphs = {kotlin_name(source.stem): read_glyph(source) for source in sources}
    except GlyphError as error:
        print(error, file=sys.stderr)
        return 1

    OUTPUT.write_text(render(glyphs), encoding='utf-8')
    print(f'{len(glyphs)} glyphs -> {OUTPUT.relative_to(ROOT)}')
    return 0


if __name__ == '__main__':
    raise SystemExit(main())
